USE [master]
GO

/****** Object:  Database [LetsMoveGirls]    Script Date: 24/04/2022 03:03:12 ******/
CREATE DATABASE [LetsMoveGirls]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LetsMoveGirls', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVERDAIANE\MSSQL\DATA\LetsMoveGirls.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LetsMoveGirls_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVERDAIANE\MSSQL\DATA\LetsMoveGirls_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LetsMoveGirls].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LetsMoveGirls] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET ARITHABORT OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LetsMoveGirls] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LetsMoveGirls] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET  ENABLE_BROKER 
GO

ALTER DATABASE [LetsMoveGirls] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LetsMoveGirls] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [LetsMoveGirls] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET RECOVERY FULL 
GO

ALTER DATABASE [LetsMoveGirls] SET  MULTI_USER 
GO

ALTER DATABASE [LetsMoveGirls] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LetsMoveGirls] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LetsMoveGirls] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LetsMoveGirls] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LetsMoveGirls] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LetsMoveGirls] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [LetsMoveGirls] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LetsMoveGirls] SET  READ_WRITE 
GO


